### ISSUE TITLE
Add-on fails to load after upgrading Kodi from v19 to v20

### ISSUE THREAD

**Issue by watchedsyncforkodi** [watchedsyncforkodi/service.watchedsync#7]
Received reports that after upgrading to Kodi v20, the add-on fails to load with error message.

Adding this issue to track.

Awaiting debug logs to investigate

**Comment by kyle-kc** [comment]
Here's the error from my debug log:

```
2023-01-20 15:42:36.534 T:15280   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kylek\AppData\Roaming\Kodi\addons\service.watchedsync\service.py", line 16, in <module>
                                                       LIB_RESOURCES_PATH = xbmc.translatePath(os.path.join(xbmcaddon.Addon().getAddonInfo('path'), 'resources', 'lib'))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

**Comment by watchedsyncforkodi** [comment]
**Attention Kodi v19 (Matrix) Users**

If you have installed this add-on **prior to 21 January 2023** then you will need to install an updated repository file (v3.0.3) to support upgrading to Kodi v20.

The updated repository file is available on [the front page](https://github.com/watchedsyncforkodi/service.watchedsync#installation)

You will need to follow installation Steps 1, 2 i) & 2 ii)

**Comment by watchedsyncforkodi** [comment]
An update to the add-on is now available that should work for Kodi v20. Follow the instructions above to install/update.

**Comment by watchedsyncforkodi** [comment]
Resolved over a year ago. Closing
